name: Build and Push Multi-Arch Docker Image

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/docker-multiarch.yml
      - requirements.txt
      - mcp_server_stdio.py
      - docker-compose.yml
      - README.md
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image with attestations
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: puregrain/proxmox-emcp:latest
          platforms: linux/amd64,linux/arm64
          # Generate provenance and SBOM attestations
          provenance: mode=max
          sbom: true

      - name: Attest Docker image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: puregrain/proxmox-emcp:latest
          subject-digest: sha256:361f1539c7b778e50581e08d586b81e8dd4b3ff7ed71de6b512ac1114be692c3
          push-to-registry: true
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          show-summary: true

      # Docker Scout Analysis
      - name: Docker Scout CVE scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: puregrain/proxmox-emcp:latest
          summary: true
          # Add platform specification to help Scout identify the image
          platform: linux/amd64
          # Continue even if Scout fails (it's informational)
        continue-on-error: true

      - name: Docker Scout comparison
        uses: docker/scout-action@v1
        with:
          command: compare
          image: puregrain/proxmox-emcp:latest
          to: puregrain/proxmox-emcp:latest
          exit-code: false
          summary: true
        continue-on-error: true

  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
