name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/docker-multiarch.yml
      - requirements.txt
      - mcp_server_stdio.py
      - mcp_server_http.py
      - docker-compose.yml
      - README.md
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image with attestations
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: puregrain/proxmox-emcp:latest
          platforms: linux/amd64,linux/arm64
          # Generate SBOM and provenance attestations
          sbom: true
          provenance: mode=max

      # Docker Scout Analysis
      - name: Docker Scout CVE scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: puregrain/proxmox-emcp:latest
          sarif-file: docker-scout-cves.sarif
          summary: true

      - name: Upload Scout results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: docker-scout-cves.sarif

      - name: Docker Scout comparison
        uses: docker/scout-action@v1
        with:
          command: compare
          image: puregrain/proxmox-emcp:latest
          to: puregrain/proxmox-emcp:latest
          exit-code: false
          summary: true

      - name: Generate SBOM
        run: syft packages docker:docker.io/puregrain/proxmox-emcp:latest -o json > sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json

  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
